[versions]
agp = "8.9.1"
kotlin = "2.0.21"
composeBom = "2023.10.01"
lottieCompose = "5.2.0"
emoji2 = "1.3.0"
ktor = "2.3.12"
kotlinxSerialization = "1.7.3"
activity = "1.12.3"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
emoji2 = { module = "androidx.emoji2:emoji2", version.ref = "emoji2" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
ui = { module = "androidx.compose.ui:ui" }
ui-text = { module = "androidx.compose.ui:ui-text" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
animation-core = { module = "androidx.compose.animation:animation-core" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }


ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }